# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_product_id', models.PositiveIntegerField()),
                ('name', models.TextField()),
                ('brand', models.TextField()),
                ('categories', models.TextField()),
                ('description', models.TextField()),
                ('material', models.TextField(blank=True)),
                ('made_in', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('site', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='spiders_app.Product'),
        ),
    ]
