# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='made_in',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.TextField(),
        ),
    ]
